# Generated by Django 5.1.3 on 2024-12-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('model', models.TextField()),
                ('year', models.DecimalField(decimal_places=5, max_digits=40)),
            ],
        ),
    ]
